### ISSUE TITLE
conextual .binMan.yaml results in error on linux

### ISSUE THREAD

**Issue by rjbrown57** [rjbrown57/binman#67]
```
panic: runtime error: index out of range [1] with length 1

goroutine 12 [running]:
github.com/rjbrown57/binman/pkg.(*BinmanRelease).getOR(0xc00021a960)
        /home/runner/work/binman/binman/pkg/binmanRelease.go:54 +0xd5
github.com/rjbrown57/binman/pkg.(*GHBMConfig).populateReleases.func1(0x6)
        /home/runner/work/binman/binman/pkg/types.go:112 +0x9a
created by github.com/rjbrown57/binman/pkg.(*GHBMConfig).populateReleases
        /home/runner/work/binman/binman/pkg/types.go:107 +0x50
```

We need to fix this issue, and add a test to prevent this kind of functionality loss in the future

**Comment by rjbrown57** [comment]
False positive. This issue existed if pre v6.0.0 binman and has since been fixed
